config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'confessions#index'
  resources :confessions
  get 'about', to: 'confessions#about'
  get 'review', to: 'confessions#review'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/confession.rb
class Confession < ApplicationRecord
	validates :saying, presence: true, length: {maximum: 500, minimum: 3}
	validates :author, presence: true, length: {maximum: 20}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/confessions_controller.rb
class ConfessionsController < ApplicationController
	before_action :authenticate_user!, only: [:update]
	def index 
		@confessionreviewed = Confession.where(reviewed:true).all.reverse
    @confession = Confession.all.reverse
	end

  	def create
  		@confession = Confession.create(confession_params) 
  		if @confession.invalid?
  			flash[:error] = 'Couldn\'t save. The saying you entered is invalid. Make sure it\'s between 3-500 characters'
  			redirect_to new_confession_path
  		end
  		if @confession.valid? 
  			redirect_to root_path
  		end
  	end

  	def about 
  	end

  	def edit
  		@confession = Confession.find(params[:id])
  	end

  	def update
  		@confession = Confession.find(params[:id])
  		@confession.update_attributes(confession_params)
  		redirect_to root_path
  	end

  	def destroy 
  		@confession = Confession.find(params[:id])
  		@confession.destroy
  		redirect_to root_path
  	end 

  	private 
  	def confession_params
  		params.require(:confession).permit(:saying, :author, :reviewed)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confessions_helper.rb
module ConfessionsHelper
end

app/views/confessions/about.html.erb
<div class="col-10 offset-1 about">
  <h1>About Cornell Crushes</h1>
  <p>
    Cornell Crushes started out as... It was built by <a target="_blank" href="">Jason</a> & <a target="_blank" href="">Iliana</a>. Two web developers who are on a mission to give people the chance to profess their love. 
  </p>
  <br />
  <p>
    Together, they... 
  </p>
  <p>
    If you want to learn how to contribute...
  </p>
</div>
<br class="clear" />
<br />
<br />
<br />
<br />

app/views/confessions/edit.html.erb
<div class="booyah-box col-10 offset-1">
<%= simple_form_for @confession do |c| %>
     <%= c.input :saying %>
     <%= c.input :author %>
     <%= c.input :reviewed, as: :boolean %> 
    <%= c.submit 'Update', class: 'btn btn-danger' %>
<% end %>
</div>

app/views/confessions/index.html.erb
<% if user_signed_in? %> 

<% @confession.each do |confession| %>
  <tr>
  <span>No. <%= confession.id %> on <%= confession.created_at.strftime("%Y-%m-%d")%> </span>
    <div class = row> 
      <div class = col-1>
          <% if confession.reviewed==true %>
            <p class = approved> Approved </p>
          <% else %>
            <p class = notapproved> Not Approved </p>
          <% end %> 
      </div>
      <div class = col-7>
        	<h3><%= confession.saying %></h3>
      </div>
      <div class = col-1>
          <%= confession.author %>
      </div>
      <div class = col-3>
          <%= link_to 'Edit', edit_confession_path(confession.id), class: 'btn btn-primary' %> 
          <%= link_to 'Delete', confession_path(confession.id), method: :delete, data: {confirm: 'Are you sure you want to delete this confession?'},class: 'btn btn-danger' %>

      </div>
    </div>
    <% end %>
       
      	</br>
        </tr>
    </div>
  <br>

<% else %> 
<% @confessionreviewed.each do |confession| %>
    <div class = "row"> 
      <div class="text-muted">No. <%= confession.id %> on <%= confession.created_at.strftime("%Y-%m-%d")%> &nbsp; &nbsp; </div>
      <div>
        <%= social_share_button_tag(confession.saying + ' — ' + confession.author, :url => confession_path(confession), desc: confession.saying) %> </div>
      </div>
      <blockquote class="blockquote">
    <h1><%= confession.saying %></h1>
  <footer class="blockquote-footer">
    <%= confession.author %>
  </footer>
    </blockquote>
  </br>
  
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crushes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if notice.present? %>
		  <p class="alert alert-info"><%= notice %></p>
		<% end %>
		<% if alert.present? %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>

  	<header class="row">
  		 <div class="col-3">
	         <div class="circle">
	        	<br />
	       		 Cornell
	        	<br />
	        	 Crushes 
	       		<br />
	        	 <3
	      	</div>
      	 </div>
      	 <div class="col-3 slogan">
	        Splurting out unsolicited advice about entrepreneurship since 2016
	     </div>
	      <div class="col-4 links">
	        <!-- Button trigger modal -->
        <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#myModal'} %>
        &nbsp;&nbsp;
	        <%= link_to 'About', about_path %>
          &nbsp;&nbsp;
	      </div>
        <ul class="col-2 navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
           <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
      <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
    </li>
      <% end %>
    </ul>
    </header>


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Dare to confess?</h4>
          </div>
          <%= simple_form_for Confession.new do |c| %>
          <div class="modal-body">
            <h1>Dare to confess?</h1>
              <%= c.input :saying, label: "I confess...", placeholder: "Jane Doe, you have the cutest smile I have ever seen." %>
              <%= c.input :author, label: "By...", placeholder: "Jake" %>
              <%= c.input :reviewed, as: :boolean %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= c.submit 'Create', class: 'btn btn-danger' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <hr />
	 <br class="clear" />
	 <div class="container">
	 	<% if flash[:error].present? %>
   			<div class="col-10 offset-1 alert alert-danger">
      			<%= flash[:error].html_safe %>
    		</div>
 		<% end %>
    <%= yield %>
	</div>
<div class="footer">
      <div class="container">
        <div class="row">
          <p class="text-muted">Place sticky footer content here.</p>
        </div>
      </div>
    </div>
  </body>
</html>